name: ai_text_organizer
description: Mobilní aplikace pro analýzu a organizaci textu pomocí Gemini AI.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  provider: ^6.0.5
  share_plus: ^7.0.2
  flutter_spinkit: ^5.2.0
  flutter_dotenv: ^5.1.0
  google_generativeai: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env